language: ruby
rvm:
  - 2.6.9
  - 2.7.5
  - 3.0.3
gemfile:
  - gemfiles/rails_5.2.gemfile
  - gemfiles/rails_6.0.gemfile
  - gemfiles/rails_6.1.gemfile
  - gemfiles/rails_7.0.gemfile
script:
  - bundle install
  - bundle exec rake spec
matrix:
  exclude:
    - rvm: 2.7.5
      gemfile: gemfiles/rails_5.2.gemfile
    - rvm: 3.0.3
      gemfile: gemfiles/rails_5.2.gemfile
