language: ruby
rvm:
  - 2.2.10
  - 2.3.7
  - 2.4.4
  - 2.5.1
gemfile:
  - gemfiles/rails_4.2.gemfile
  - gemfiles/rails_5.0.gemfile
  - gemfiles/rails_5.1.gemfile
  - gemfiles/rails_5.2.gemfile
before_install: gem install bundler -v 1.16.1
script:
  - bundle install
  - bundle exec rake spec
