language: ruby
rvm:
  - 2.0.0
  - 2.1.0
  - 2.2.2
  - 2.3.0
  - 2.4.0
gemfile:
  - gemfiles/rails_4.0.gemfile
  - gemfiles/rails_4.1.gemfile
  - gemfiles/rails_4.2.gemfile
  - gemfiles/rails_5.0.gemfile
  - gemfiles/rails_5.1.gemfile
matrix:
  exclude:
    - rvm: 2.0.0
      gemfile: gemfiles/rails_5.0.gemfile
    - rvm: 2.0.0
      gemfile: gemfiles/rails_5.1.gemfile
    - rvm: 2.1.0
      gemfile: gemfiles/rails_5.0.gemfile
    - rvm: 2.1.0
      gemfile: gemfiles/rails_5.1.gemfile
    - rvm: 2.4.0
      gemfile: gemfiles/rails_4.0.gemfile
    - rvm: 2.4.0
      gemfile: gemfiles/rails_4.1.gemfile
before_install: gem install bundler -v 1.10.5
script:
  - bundle install
  - bundle exec rake spec
