language: ruby
rvm:
  - 2.4.6
  - 2.5.5
  - 2.6.3
  - 2.7.0-preview1
gemfile:
  - gemfiles/rails_4.2.gemfile
  - gemfiles/rails_5.0.gemfile
  - gemfiles/rails_5.1.gemfile
  - gemfiles/rails_5.2.gemfile
  - gemfiles/rails_6.0.gemfile
script:
  - bundle install
  - bundle exec rake spec
matrix:
  exclude:
    - rvm: 2.4.6
      gemfile: gemfiles/rails_6.0.gemfile
  allow_failures:
    rvm: 2.7.0-preview1
